package Modelo;
// Generated 20/09/2018 05:26:25 PM by Hibernate Tools 4.3.1



/**
 * Person generated by hbm2java
 */
public class Person  implements java.io.Serializable {


     private long id;
     private String name;

    public Person() {
    }

	
    public Person(long id) {
        this.id = id;
    }
    public Person(long id, String name) {
       this.id = id;
       this.name = name;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


